"""add product variants

Revision ID: 8548b5f63ae5
Revises: dfb3aa333c39
Create Date: 2026-08-31 14:24:58.225513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8548b5f63ae5'
down_revision: Union[str, Sequence[str], None] = 'dfb3aa333c39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_variants_product_id'), 'product_variants', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_variants_sku'), 'product_variants', ['sku'], unique=True)
    op.add_column('inventory', sa.Column('variant_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('inventory_product_id_key'), 'inventory', type_='unique')
    op.create_unique_constraint(None, 'inventory', ['variant_id'])
    op.drop_constraint(op.f('inventory_product_id_fkey'), 'inventory', type_='foreignkey')
    op.create_foreign_key(None, 'inventory', 'product_variants', ['variant_id'], ['id'])
    op.drop_column('inventory', 'product_id')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_column('products', 'price')
    op.drop_column('products', 'currency')
    op.drop_column('products', 'sku')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('sku', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.add_column('inventory', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.create_foreign_key(op.f('inventory_product_id_fkey'), 'inventory', 'products', ['product_id'], ['id'])
    op.drop_constraint(None, 'inventory', type_='unique')
    op.create_unique_constraint(op.f('inventory_product_id_key'), 'inventory', ['product_id'])
    op.drop_column('inventory', 'variant_id')
    op.drop_index(op.f('ix_product_variants_sku'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_product_id'), table_name='product_variants')
    op.drop_table('product_variants')
    # ### end Alembic commands ###
